# Generated by Django 3.1.5 on 2021-01-29 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('arguments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConvertJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=1000)),
                ('destination', models.CharField(max_length=1000)),
                ('custom_arguments', models.TextField()),
                ('log', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
                ('error_text', models.TextField()),
                ('time_left', models.CharField(max_length=50)),
                ('speed', models.IntegerField()),
                ('total_length_seconds', models.IntegerField()),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffmpeg_web.preset')),
            ],
        ),
    ]
