# Generated by Django 3.1.5 on 2021-01-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
