# Generated by Django 3.1.5 on 2021-01-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg_web', '0002_auto_20210129_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertjob',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='convertjob',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='convertjob',
            name='total_length_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
