# Generated by Django 3.1.5 on 2021-01-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg_web', '0003_auto_20210130_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertjob',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
