# Generated by Django 3.1.5 on 2021-02-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg_web', '0004_auto_20210130_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertjob',
            name='log',
        ),
    ]
